homepage:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: easyadmin, permanent: true }

backend:
    resource: '../src/Controller/'
    prefix: /admin
    type: annotation
