parameters:
    locale: 'en'
    app.path.product_images: /uploads/images/products
    app.path.user_contracts: /uploads/files/user/contracts

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # TEMPORARY FIX until this is solved: https://github.com/egeloen/IvoryCKEditorBundle/issues/323
    ivory_ck_editor.renderer.json_builder:
        class: Ivory\JsonBuilder\JsonBuilder
        arguments: ['@property_accessor']
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Repository,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
